title: "Encyclopedia Ambura"
description: "A reference guide for the world of Ambura."
baseurl: ""
url: "http://example.com"
theme: "null"
# defaultFileName: "default.html" 
collections:
  terms:
    output: true  # This tells Jekyll to generate a list/index for this collection